"""
Report Generator — GridGuard AI Python Automation Toolkit

Generates clean Markdown reports from CSV or JSON data.
Includes optional summary statistics. No heavy dependencies.

Usage:
    python -m toolkit.pdf_reporter --data FILE.csv --title "My Report" --output report.md
    python -m toolkit.pdf_reporter --data FILE.json --title "Metrics" --summary --output report.md
"""

import argparse
import csv
import json
import os
import sys
from datetime import datetime
from typing import Dict, List, Tuple


def load_csv(path):
    # type: (str) -> Tuple[List[str], List[Dict]]
    with open(path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        columns = list(rows[0].keys()) if rows else []
    return columns, rows


def load_json(path):
    # type: (str) -> Tuple[List[str], List[Dict]]
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if isinstance(data, list) and data and isinstance(data[0], dict):
        columns = list(data[0].keys())
        return columns, data
    elif isinstance(data, dict):
        return list(data.keys()), [data]
    else:
        print("[reporter] Unsupported JSON structure. Expected list of objects or object.")
        sys.exit(1)


def load_data(path):
    # type: (str) -> Tuple[List[str], List[Dict]]
    ext = os.path.splitext(path)[1].lower()
    if ext == ".csv":
        return load_csv(path)
    elif ext == ".json":
        return load_json(path)
    else:
        print("[reporter] Unsupported file type: {}. Use .csv or .json.".format(ext))
        sys.exit(1)


def make_table(columns, rows):
    # type: (List[str], List[Dict]) -> str
    """Build a Markdown table from columns and rows."""
    if not rows:
        return "*No data.*\n"

    header = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join("---" for _ in columns) + " |"

    lines = [header, sep]
    for row in rows:
        vals = []
        for col in columns:
            val = str(row.get(col, "")).replace("|", "\\|").replace("\n", " ")
            vals.append(val)
        lines.append("| " + " | ".join(vals) + " |")

    return "\n".join(lines) + "\n"


def compute_summary(columns, rows):
    # type: (List[str], List[Dict]) -> str
    """Compute basic stats for numeric columns."""
    sections = []

    for col in columns:
        values = []
        for row in rows:
            raw = row.get(col, "")
            try:
                values.append(float(raw))
            except (ValueError, TypeError):
                continue

        if len(values) < 2:
            continue

        total = sum(values)
        avg = total / len(values)
        mn = min(values)
        mx = max(values)

        sections.append(
            "**{}**\n"
            "- Count: {}\n"
            "- Sum: {:,.2f}\n"
            "- Mean: {:,.2f}\n"
            "- Min: {:,.2f}\n"
            "- Max: {:,.2f}\n".format(col, len(values), total, avg, mn, mx)
        )

    if not sections:
        return "*No numeric columns found for summary.*\n"

    return "\n".join(sections)


def generate_report(title, columns, rows, include_summary=False, source=""):
    # type: (str, List[str], List[Dict], bool, str) -> str
    """Build the full Markdown report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    parts = [
        "# {}\n".format(title),
        "*Generated: {}*  ".format(now),
    ]
    if source:
        parts.append("*Source: {}*  ".format(source))
    parts.extend([
        "*Rows: {} | Columns: {}*\n".format(len(rows), len(columns)),
        "---\n",
        "## Data\n",
        make_table(columns, rows),
    ])

    if include_summary:
        parts.append("\n---\n")
        parts.append("## Summary Statistics\n")
        parts.append(compute_summary(columns, rows))

    parts.append("\n---\n")
    parts.append("*Report generated by GridGuard AI Python Automation Toolkit*\n")

    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(
        description="Generate Markdown reports from CSV or JSON data."
    )
    parser.add_argument("--data", required=True, help="Input data file (.csv or .json)")
    parser.add_argument("--title", default="Report", help="Report title")
    parser.add_argument("--output", default=None, help="Output .md file (omit to print to stdout)")
    parser.add_argument("--summary", action="store_true", help="Include summary statistics")

    args = parser.parse_args()

    columns, rows = load_data(args.data)
    print("[reporter] Loaded {} rows, {} columns from {}".format(len(rows), len(columns), args.data))

    report = generate_report(
        title=args.title,
        columns=columns,
        rows=rows,
        include_summary=args.summary,
        source=os.path.basename(args.data),
    )

    if args.output:
        parent = os.path.dirname(args.output)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(report)
        print("[reporter] Report saved to {}".format(args.output))
    else:
        print()
        print(report)


if __name__ == "__main__":
    main()
